project:
  type: book

book:
  title: "trainingslageR"
  subtitle: "Ein Übungsbuch für R-Einsteiger*innen"
  language: de
  author:
    - name: Prof. Dr. Jörg große Schlarmann
      url: https://www.produnis.de/R
      affiliation: Hochschule Niederrhein
      affiliation-url: https://www.hs-niederrhein.de
      orcid: 0000-0002-3634-7722
  date: "2024-06-27"
  chapters:
    - index.qmd
    - aufgaben.qmd
    - loesungen.qmd
    - literatur.qmd
    - credits.qmd

bibliography: literatur.bib
nocite: |
  @waltherR22, @tidytuesday, @Rbase

freeze: auto

format:
    pdf:
      documentclass: scrreprt
      papersize: a4paper
      fontsize: 11pt
      geometry:
        - top=30mm
        - bottom=30mm
        - left=20mm
        - right=20mm
        - headsep=15mm
      df-print: kable
      code-line-numbers: false # false
      keep-tex: false # true # false
      lang: de
      date-format: "DD.MM.YYYY"
      linkcolor: black
      logowidth: 101.4mm
      logo: _extensions/buechlein/HSNRfb10.png
      toc: false
      lof: false
      lot: false
      csl: _extensions/buechlein/apa-single-spaced.csl
      include-in-header: _extensions/buechlein/in-header.tex   # header
      template-partials:
        - _extensions/buechlein/title.tex
        - _extensions/buechlein/before-body.tex

