project:
  type: book
  output-dir: BOOK
  resources:
    - data

author:
    - name: Prof. Dr. Jörg große Schlarmann
      url: https://www.produnis.de/R
      affiliation: Hochschule Niederrhein
      affiliation-url: https://www.hs-niederrhein.de
      orcid: 0000-0002-3634-7722

citation:
  type: book
  title: "trainingslageR"
  publisher: "Hochschule Niederrhein"
  publisher-place: "Krefeld"
  language: de
  status: "advance online publication"
  license: "CC BY-NC-SA 4.0"
  url: https://github.com/produnis/trainingslager
  public-url: https://www.produnis.de/trainingslager
  fulltext-url: https://www.produnis.de/trainingslager

book:
  title: "trainingslageR"
  subtitle: "Ein Übungsbuch für R-Einsteiger:innen und Fortgeschrittene"
  language: de
  author:
    - name: Prof. Dr. Jörg große Schlarmann
      url: https://www.produnis.de/R
      affiliation: Hochschule Niederrhein
      affiliation-url: https://www.hs-niederrhein.de
      orcid: 0000-0002-3634-7722
  date: "2024-10-16"
  date-format: "DD.MM.YYYY"
  cover-image: images/Titelbild.png
  output-file: trainingslager
  sidebar:
    collapse-level: 4
  downloads:
    - pdf
    - epub
  open-graph:
    image: "https://www.produnis.de/trainingslager/images/Titelbild.png"
    locale: de_DE
  twitter-card:
    image: "https://www.produnis.de/trainingslager/images/Titelbild.png"
    creator: "produnis"
  chapters:
    - index.qmd
    - einleitung.qmd
    - part: "Aufgaben"
      chapters:
        - anfaenger-aufgaben.qmd
        - geuebte-aufgaben.qmd
        - fortgeschritten-aufgaben.qmd
    - part: "Lösungswege"
      chapters:
        - anfaenger-loesungen.qmd
        - geuebte-loesungen.qmd
        - fortgeschritten-loesungen.qmd
    - literatur.qmd
    - credits.qmd

bibliography: literatur.bib
csl: apa-single-spaced.csl
nocite: |
  @waltherR22, @tidytuesday, @Rbase, @wickham23
lang: de

language:
  crossref-sec-prefix: "Abschnitt"
  crossref-chap-prefix: "Abschnitt"
freeze: auto

format:
    buechlein-html: default
    buechlein-epub: default
    buechlein-pdf: default
