project:
  type: book
  output-dir: BOOK
  resources:
    - data

author:
    - name: Prof. Dr. Jörg große Schlarmann
      url: https://www.produnis.de/R
      affiliation: Hochschule Niederrhein
      affiliation-url: https://www.hs-niederrhein.de
      orcid: 0000-0002-3634-7722

citation:
  type: book
  title: "trainingslageR"
  publisher: "Hochschule Niederrhein"
  publisher-place: "Krefeld"
  language: de
  status: "advance online publication"
  license: "CC BY-NC-SA 4.0"
  url: https://github.com/produnis/trainingslager
  public-url: https://www.produnis.de/trainingslager
  fulltext-url: https://www.produnis.de/trainingslager
  pdf-url: https://www.produnis.de/trainingslager/trainingslageR.pdf

book:
  title: "trainingslageR"
  subtitle: "Ein Übungsbuch für R-Einsteiger:innen und Fortgeschrittene"
  language: de
  author:
    - name: Prof. Dr. Jörg große Schlarmann
      url: https://www.produnis.de/R
      affiliation: Hochschule Niederrhein
      affiliation-url: https://www.hs-niederrhein.de
      orcid: 0000-0002-3634-7722
  date: "2024-10-16"
  date-format: "DD.MM.YYYY"
  description:  |
    In diesem Buch sind zahlreiche Übungen zur freien Statistiksoftware R enthalten, die vor allem für Studierende im Gesundheitswesen von Nutzen sein könnten.
  favicon: images/favicon.ico
  cover-image: images/Titelbild.jpg
  output-file: trainingslageR
  sidebar:
    collapse-level: 4
  downloads:
    - pdf
    - epub
  open-graph:
    image: "https://www.produnis.de/trainingslager/images/Titelbild.jpg"
    locale: de_DE
  twitter-card:
    image: "https://www.produnis.de/trainingslager/images/Titelbild.jpg"
    creator: "produnis"
  chapters:
    - index.qmd
    - einleitung.qmd
    - part: "Aufgaben"
      chapters:
        - anfaenger-aufgaben.qmd
        - geuebte-aufgaben.qmd
        - fortgeschritten-aufgaben.qmd
    - part: "Lösungswege"
      chapters:
        - anfaenger-loesungen.qmd
        - geuebte-loesungen.qmd
        - fortgeschritten-loesungen.qmd
    - literatur.qmd
    - credits.qmd
  page-footer:
    right:
      - icon: github
        href: https://github.com/produnis/trainingslager
      - icon: linkedin
        href: https://www.linkedin.com/in/j%C3%B6rg-gro%C3%9Fe-schlarmann-32b3331b7/
      - icon: mastodon
        href: https://mastodon.social/@rbuch
      - icon: file-earmark-pdf
        href: trainingslageR.pdf
      - icon: journal-richtext
        href: trainingslageR.epub

bibliography: literatur.bib
csl: apa-single-spaced.csl
nocite: |
  @waltherR22, @tidytuesday, @Rbase, @wickham23
lang: de

language:
  crossref-sec-prefix: "Abschnitt"
  crossref-chap-prefix: "Abschnitt"
freeze: auto

format:
    buechlein-html: default
    buechlein-epub: default
    buechlein-pdf: default
