project:
  type: book
  output-dir: PDF

author:
    - name: Prof. Dr. Jörg große Schlarmann
      url: https://www.produnis.de/R
      affiliation: Hochschule Niederrhein
      affiliation-url: https://www.hs-niederrhein.de
      orcid: 0000-0002-3634-7722

citation:
  type: book
  title: "trainingslageR"
  publisher: "Hochschule Niederrhein"
  publisher-place: "Krefeld"
  language: de
  status: "advance online publication"
  license: "CC BY-NC-SA 4.0"

book:
  title: "trainingslageR"
  subtitle: "Ein Übungsbuch für R-Einsteiger:innen und Fortgeschrittene"
  language: de
  author:
    - name: Prof. Dr. Jörg große Schlarmann
      url: https://www.produnis.de/R
      affiliation: Hochschule Niederrhein
      affiliation-url: https://www.hs-niederrhein.de
      orcid: 0000-0002-3634-7722
  date: "2024-07-03"
  date-format: "DD.MM.YYYY"
  chapters:
    - index.qmd
    - einleitung.qmd
    - part: "Aufgaben"
      chapters:
        - anfaenger-aufgaben.qmd
        - geuebte-aufgaben.qmd
        - fortgeschritten-aufgaben.qmd
    - part: "Lösungswege"
      chapters:
        - anfaenger-loesungen.qmd
        - geuebte-loesungen.qmd
        - fortgeschritten-loesungen.qmd
    - literatur.qmd
    - credits.qmd

bibliography: literatur.bib
nocite: |
  @waltherR22, @tidytuesday, @Rbase, @wickham23
csl: _src/apa-single-spaced.csl

language:
  crossref-sec-prefix: "Abschnitt"
  crossref-chap-prefix: "Abschnitt"
freeze: auto

format:
    epub:
      theme: default
      toc: true
      rights: "Creative Commons BY-NC-SA 4.0"
      code-line-numbers: false
    pdf:
      documentclass: scrreprt
      papersize: a4paper
      fontsize: 11pt
      geometry:
        - top=20mm
        - bottom=25mm
        - left=15mm
        - right=15mm
        - headsep=10mm
      lang: de
      linkcolor: black
      link-citations: true
      toc: false
      lof: false
      lot: false
      df-print: default
      code-line-numbers: false
      keep-tex: false # true # false
      include-in-header: _src/in-header.tex
      template-partials:
        - _src/title.tex
        - _src/before-body.tex

